version: '3'
services:
  backup:
    image: sdmoradi/database-backup-s3:latest
    environment:
      - JOBNAME=backup-rocketchat
      - DATABASE_TYPE=mongodb
      - DATABASE_ADDRESS=ip
      - DATABASE_PORT=27017
      - DATABASE_USER=user
      - DATABASE_PASS=password
      - DATABASE_NAME=dbname
      - S3_ADDRESS=s3address
      - S3_PORT=443
      - S3_SECRET=secret
      - S3_ACCESS=access
      - S3_BUCKET=backups
      - S3_PATH=db-backups
      - S3_LIFECYCLE=7
networks:
  default:
    name: database