---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.jobname }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.jobname }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - image: sdmoradi/database-backup-s3:latest
              envFrom:
                - secretRef:
                    name: {{ .Values.jobname }}-secret
              imagePullPolicy: IfNotPresent
              name: database-backup
              resources: {}
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 1
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: 2
  suspend: false