apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.jobname }}-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  JOBNAME: {{ .Values.jobname | b64enc }}
  DATABASE_TYPE: {{ .Values.database.type | b64enc }}
  DATABASE_ADDRESS: {{ .Values.database.address | b64enc }}
  DATABASE_PORT: {{ .Values.database.port | b64enc }}
  DATABASE_USER: {{ .Values.database.user | b64enc }}
  DATABASE_PASS: {{ .Values.database.password | b64enc }}
  DATABASE_NAME: {{ .Values.database.name | b64enc }}
  S3_ADDRESS: {{ .Values.s3.address | b64enc }}
  S3_PORT: {{ .Values.s3.port | b64enc }}
  S3_SECRET: {{ .Values.s3.secret | b64enc }}
  S3_ACCESS: {{ .Values.s3.access | b64enc }}
  S3_BUCKET: {{ .Values.s3.bucket | b64enc }}
  S3_PATH: {{ .Values.s3.path | b64enc }}
  S3_LIFECYCLE: {{ .Values.s3.lifecycle | b64enc }}