---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "database-backup.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "database-backup.name" . }}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
              image: sdmoradi/database-backup-s3:latest
              env:
                - name: DATABASE_TYPE
                  value: {{ .Values.database.type }}
                - name: DATABASE_ADDRESS
                  value: {{ .Values.database.address }}
                - name: DATABASE_PORT
                  value: {{ .Values.database.port }}
                - name: DATABASE_USER
                  value: {{ .Values.database.user }}
                - name: DATABASE_PASS
                  value: {{ .Values.database.password }}
                - name: DATABASE_NAME
                  value: {{ .Values.database.name }}
                - name: S3_ADDRESS
                  value: {{ .Values.s3.address }}
                - name: S3_PORT
                  value: {{ .Values.s3.port }}
                - name: S3_SECRET
                  value: {{ .Values.s3.secret }}
                - name: S3_ACCESS
                  value: {{ .Values.s3.access }}
                - name: S3_BUCKET
                  value: {{ .Values.s3.bucket }}
                - name: S3_PATH
                  value: {{ .Values.s3.path }}
              imagePullPolicy: Always
              name: database-backup
              resources: {}
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      ttlSecondsAfterFinished: 1
  schedule: {{ .Values.schedule }}
  successfulJobsHistoryLimit: 2
  suspend: false